### PR TITLE
update mockup

### PR DESCRIPTION
**Pull request by pbauer**
Done to include https://github.com/plone/mockup/pull/1005

### CODE REVIEW

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
I'm kinda lost with the crazy multitude of steps I need to do. Does this PR make sense at all if mockup 3.2.2 is not yet released?

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
Thanks for merging!

**Comment by vincentfretin** [comment]
When doing the bundles for Plone 5.1 with the the bower package manager, I found out that mockup is not a dependency in Products/CMFPlone/static/bower.json. When we switched from bower to yarn, the bower.json was replaced by a package.json in plone.staticresources, with mockup as a dependency. But I think this is really to get all the mockup dependencies in the components folder. Declaring all mockup dependencies in plone.staticresources/package.json instead of having the mockup dependency (similar to what we had between mockup-2.7/bower.json and Products/CMFPlone/static/bower.json) may be clearer. At least there will be no need to add mockup changes in the components folder and the confusion of using a non released version of mockup. Moreover when you are in develop mode, the real code used is src/mockup, not plone/staticresources/components/mockup.
If we go to simplify the procedure and declare mockup dependencies instead of mockup in package.json, the only thing we would lose is the mockup commit hash from where the bundles were generated. We may add a file to track that as I think it's a useful info.

**Comment by thet** [comment]
@vincentfretin the components folder is only necessary for compiling bundles through-the-web in the @@resourceregistry-controlpanel.
You're right, when in development mode and mockup is manually installed with ``yarn install``, IIRC the resources there would/should be used.
I'd prefer to only declare the mockup dependency in the correct version, otherwise we would need to maintain and sync the package.json files in mockup AND plone.staticresources.

**Pull request merged**
