### PR TITLE
Fixes plone/mockup#895 again.

### PR DESCRIPTION
**Pull request by fulv**

### CODE REVIEW

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by davilima6** [comment]
@fulv, I dropped the first commit with an interactive rebase, tested locally, push forced and now triggered tests. Once green, I'll merge.

**Comment by davilima6** [comment]
All 3 Jenkins jobs failed in one seemingly unrelated p.a.users test:

* https://jenkins.plone.org/job/pull-request-5.2/259/testReport/plone.app.users.tests.test_pam/TestUserDataPanelWithPAM/test_pam/
* https://jenkins.plone.org/job/pull-request-5.2-3.6/244/testReport/plone.app.users.tests.test_pam/TestUserDataPanelWithPAM/test_pam/
* https://jenkins.plone.org/job/pull-request-5.2-3.7/233/testReport/plone.app.users.tests.test_pam/TestUserDataPanelWithPAM/test_pam/

**Comment by ale-rt** [comment]
I would just ignore that, see:
- https://github.com/plone/plone.app.users/issues/78
I am trying to understand more with this probe PR https://github.com/plone/plone.app.users/pull/79

**Comment by davilima6** [comment]
Thanks, @ale-rt!

**Pull request merged**
