### PR TITLE
Build bundles for mockup 3.x, commit e84d2f4f58628897a7a1754bc07478b014907dd0

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This contains the changes until and including https://github.com/plone/mockup/commit/e84d2f4f58628897a7a1754bc07478b014907dd0

This replaces my PR #104.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Reverted a commit in mockup 3.x, updated bundles again.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Yes! It is finally green.

**Comment by mauritsvanrees** [comment]
Jenkins is green. I merge.

**Comment by petschki** [comment]
some more notes on this: we're experiencing problems with mosaic modals, eg. you cannot remove a criteria in the `existingcontenttile` modal anymore and the path navigation in `relateditemspattern` in modals is completely broken like @mauritsvanrees mentioned above. With deactivated `self.activateFocusTrap();``everything works like it should agaign.

**Pull request merged**
