### PR TITLE
Split up bundles

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
Bundle sizes old:

```
130K    plone-base-compiled.js
 42K    plone-base-compiled.min.js
229K    plone-compiled.css
663K    plone-compiled.js
269K    plone-compiled.min.js
716K    plone-logged-in-compiled.css
3.1M    plone-logged-in-compiled.js
1.3M    plone-logged-in-compiled.min.js
```

Bundle sizes new:
```
130K    plone-base-compiled.js
 41K    plone-base-compiled.min.js
166K    plone-compiled.css
222K    plone-compiled.js
 86K    plone-compiled.min.js
584K    plone-datatables-compiled.js
207K    plone-datatables-compiled.min.js
225K    plone-editor-tools-compiled.css
1.1M    plone-editor-tools-compiled.js
442K    plone-editor-tools-compiled.min.js
3.8K    plone-legacy-compiled.css
 14K    plone-legacy-compiled.js
265K    plone-logged-in-compiled.css
375K    plone-logged-in-compiled.js
161K    plone-logged-in-compiled.min.js
 62K    plone-moment-compiled.js
 55K    plone-moment-compiled.min.js
225K    plone-tinymce-compiled.css
2.4M    plone-tinymce-compiled.js
966K    plone-tinymce-compiled.min.js
```

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@davilima6 lazy loading of moment locales is still a bit odd
If I create a new site in german, documentByLine says ...  zuletzt geändert: 4 minutes ago 
When I turn on/off development mode in the resource registry, it seems to work sometimes.
If I add multilingual and more languages, the moment locales load most of the time, but don't seem to be active or really localize the date.
Any idea?

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by MrTango** [comment]
@jenkins-plone-org please run jobs

**Comment by davilima6** [comment]
@agitator, no idea but if you could please file an issue I'll try to look over the next days.

**Comment by thet** [comment]
@davilima6 looks like the problem was already present with 5.2 / plone.staticresources merge.
Since it's only moment is only used very sparsely (document_byline and structure pattern IIRC) @agitator will prepare a PLIP for removing moment alltogether.

**Comment by davilima6** [comment]
Since it's likely addons rely on moment, maybe it's nice to leave it available as a resource, while uninstalled, until our next Plone major. What do you think?

**Comment by agitator** [comment]
that's exactly our plan ;-)

**Pull request merged**
