### PR TITLE
Move fonts to extra bundle

### PR DESCRIPTION
**Pull request by agitator**
Reduce bundle sizes by not inlining fonts in each bundle - moved plone-fontello and glyphicons to their own bundle.

Depends on: https://github.com/plone/mockup/pull/1042

This PR adds two new bundles: plone-fontello and plone-glyphicons.

The total CSS size is reduced about 700kB.

CSS bundle sizes before this PR:
```
224K	filemanager-compiled.css
168K	plone-compiled.css
16K	plone-datatables-compiled.css
232K	plone-editor-tools-compiled.css
4.0K	plone-legacy-compiled.css
268K	plone-logged-in-compiled.css
376K	plone-tinymce-compiled.css
204K	resourceregistry-compiled.css
248K	thememapper-compiled.css
4.0K	tinymce-styles.css
1.8M	total
```

CSS bundle sizes with this PR:
```
104K	filemanager-compiled.css
20K	plone-compiled.css
16K	plone-datatables-compiled.css
116K	plone-editor-tools-compiled.css
32K	plone-fontello-compiled.css
120K	plone-glyphicons-compiled.css
4.0K	plone-legacy-compiled.css
148K	plone-logged-in-compiled.css
256K	plone-tinymce-compiled.css
84K	resourceregistry-compiled.css
132K	thememapper-compiled.css
4.0K	tinymce-styles.css
1.1M	total
```

### CODE REVIEW

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Review by thet — APPROVED** [review]
I've updated this PR to install the mockup PR version and compile all bundles.
Looks good to me/.

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@mauritsvanrees should we try to remove the inlining of web fonts? The way it works now is that about 4 types of web fonts are included in the file rather than the one a specific browser needs...

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
@agitator wrote:
> @mauritsvanrees should we try to remove the inlining of web fonts?

I have no opinion on this. I think you already did that in a later commit, right?

In total, LGTM, though I did not try it out.

Do add-on developers need to change something because of this PR?

**Review by mauritsvanrees — APPROVED** [review]

**Comment by agitator** [comment]
the changes shouldn't have an impact for addons
@mauritsvanrees could you do a release?

**Comment by mauritsvanrees** [comment]
Yes, I can. I have added mockup and staticresources to the checkouts first.

**Comment by agitator** [comment]
wait with releasing, maybe found something...

**Pull request merged**
