### PR TITLE
Update Bootstrap Icons

### PR DESCRIPTION
**Pull request by santonelli**
This just updates the Bootstrap Icons from 1.0.0-alpha3 to 1.0.0. Changes for Plone 6 has been moved to the branch `barceloneta-lts`

### CODE REVIEW

**Comment by santonelli** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — COMMENTED** [review]
Sounds sane and safe, but I don't really know what I am looking at. I don't know this corner of Plone.

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by thet — APPROVED** [review]
LGTM

**Pull request merged**
