### PR TITLE
Update to latest mockup and build all bundles

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@mauritsvanrees @thet the new added profile `plone.staticresources.upgrades:8` isn't in the hidden profiles list ... I'll prepare a bugfix PR right now

**Comment by thet** [comment]
@petschki tnx! just add the commit to this PR. Is it the reason why jenkins fails with this PR?

**Comment by petschki** [comment]
> Is it the reason why jenkins fails with this PR?

Same reason ... simply rebase this one, when #84 is green and merged

**Comment by mauritsvanrees** [comment]
I have merged #84 and am confident this fixes the errors in the current PR, so I will merge this one too. Thanks both!

**Pull request merged**
