### PR TITLE
Fix icon font loading

### PR DESCRIPTION
**Pull request by thet**
Fix issue with Glyphicons and Fontello font loading on Portals where the portal root is a level higher.
The fonts are now loaded relative to the CSS requesting them.

Fixes: https://github.com/plone/plone.staticresources/issues/162
Fixes: https://github.com/plone/plone.staticresources/issues/203

Ref: https://github.com/plone/plone.staticresources/pull/168
Ref: https://github.com/plone/plone.staticresources/pull/171
Ref: https://github.com/plone/plone.staticresources/pull/175
Ref: https://community.plone.org/t/deployments-not-rooted-fail-to-load-the-fontello-icons/15047/12?u=thet

@sneridagh @agitator @yurj @cekk please review this PR if it fixes the font loading problem for you and for not introducing new errors.

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]
LGTM!

**Comment by mauritsvanrees** [comment]
Thanks @thet!

Yes, I want to release Plone 5.2.8 in April, so this would be welcome.

**Comment by erral** [comment]
I have installed the 1.x branch in a client's site running Plone 5.2.7, and after running the upgrade step the icons are showing OK in both deployment scenarios (full domain and a path under the domain) and with debug mode on and off.

**Comment by sneridagh** [comment]
@mauritsvanrees could we have a release so we can apply it right away? It would be great! Thanks!

**Pull request merged**
