### PR TITLE
Mockup update

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@plone/ci-team would you be so kind and activate GHA for this repository?

**Comment by davisagli** [comment]
@petschki What do you mean exactly? There's no activation needed for GHA, you activate it by adding files in `.github/workflows` to define the workflows you want to run.

**Comment by petschki** [comment]
@davisagli since configuring with [plone/meta](https://github.com/plone/meta) the activation has to be done manually, because the config files lying there. I do not know exactly the workflow but this is how its was done in `plonetheme.barceloneta` too by @jensens ... @gforcada or @mauritsvanrees might have more insights on this too ...

**Comment by davisagli** [comment]
I see, the request was for activating plone/meta, not GHA in general.

**Comment by mauritsvanrees** [comment]
@petschki Done.

**Pull request merged**
