### PR TITLE
Mockup updates

### PR DESCRIPTION
**Pull request by petschki**
needs https://github.com/plone/plone.schemaeditor/pull/92 ... Jenkins parameters:

```
https://github.com/plone/plone.schemaeditor/pull/92
https://github.com/plone/plone.staticresources/pull/239
```

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Oops, I should have merged this together with https://github.com/plone/plone.schemaeditor/pull/92. Doing so now.

**Pull request merged**
