### PR TITLE
TinyMCE 7

### PR DESCRIPTION
**Pull request by petschki**
lets see what breaks

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by thet — CHANGES_REQUESTED** [review]
I did briefly check this version by adding some custom header, character style and listing formats and trying out the image editor. Everything seems to work.

IMO this is something for Plone 6.1, right?

Please add a newas entry - thats currently the only issue with this PR.

**Comment by petschki** [comment]
yes, master is for Plone 6.1 ... but it can safely be used in 6.0 too by pinning to the latest `2.2.x` manually (including barceloneta `3.2.x` and mosaic `3.2.x` )

I'll do a mockup release with the latest tinymce resources and fix this PR with news entry aftewards.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by thet — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]
LGTM.  Let's ship it. :-)

If you release this and Barceloneta, I can do a Plone 6.1.0a3 release today (Friday).

**Comment by petschki** [comment]
Will do! First some package housekeeping, then release.

**Pull request merged**
