### PR TITLE
TinyMCE 6 upgrade

### PR DESCRIPTION
**Pull request by petschki**
~~Wait for merged and released https://github.com/plone/mockup/pull/1346~~

prerelease `mockup==5.2.0.alpha.0`

~~This also needs updated config settings for the "formats" menu in `plone.base` (https://github.com/plone/plone.base/blob/main/src/plone/base/interfaces/controlpanel.py#L605) and an upgrade step in `plone.app.upgrades`~~

we've mapped the old plugin names with the new one in mockup. works OOTB now. The configuration values should still be changed in Plone 6.1 though. But no need for an upgrade step so far.

As this bumps the version of mockup to `5.2.x` we should bump it here to `2.2.x` too and target Plone 6.1 ... but its of course compatible with Plone 6.0 too.

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Seems to work fine.  Thanks!
As you said on Discord, should be for Plone 6.1.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
