### PR TITLE
Upgrade Bootstrap to 5.1.1

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@mauritsvanrees do you have any clue, why jenkins gets an error with this PR?

**Comment by petschki** [comment]
sorry... the upgrade profile wasn't hidden. fixed that.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I get the same error locally with this branch, and not with master, so that helps:

```
$ bin/test -s Products.CMFPlone -t test_addons_controlpanel_install_and_uninstall_all
...
Failure in test test_addons_controlpanel_install_and_uninstall_all (Products.CMFPlone.controlpanel.tests.test_controlpanel_browser_installer.AddonsControlPanelFunctionalTest)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.CMFPlone/Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_installer.py", line 110, in test_addons_controlpanel_install_and_uninstall_all
    self.browser.getControl('Install', index=0)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 226, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 163, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: LookupError not raised
```

The test sees there are three Install buttons for add-ons, it clicks on all of them, and then it checks that no Install buttons are left, so we expect a LookupError. On this branch there *is* an Install button left.

Ah, when I look at the browser contents, I see that with your branch there is an extra Install button, for "Update bundles" (`plone.staticresources.upgrades`). Probably clicking on it has no effect, or not the desired effect.

Ah, I see a new commit coming in, which seems to fix this. :-)

**Comment by petschki** [comment]
sry for the noise 🙈

**Comment by mauritsvanrees** [comment]
No problem. :-)

**Review by agitator — APPROVED** [review]
lgtm

**Pull request merged**
