### PR TITLE
Use successor repository of `svg-country-flags`

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
still draft? LGTM so far.

**Comment by petschki** [comment]
The "Netherlands Antilles" got deleted somehow in this repo ... as long as its not critical to us we can merge it. I wanted to file an issue there and see whats the response.

**Comment by petschki** [comment]
ok, found this issue there: https://github.com/hampusborgos/country-flags/issues/54 ... explanation why removed.

**Pull request merged**
