### PR TITLE
Register Patternslib resources

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by ale-rt** [comment]
I went to http://localhost:8080/Plone/portal_setup/manage_fullImport and installed `profile-plone.staticresources:patternslib`.
After that, visiting a page, I see a 404 for this resource: http://localhost:8080/Plone/++plone++static/++unique++2015-11-23%2022%3A55%3A00/patterns-compiled.min.js
After importing the `profile-plone.staticresources:patternslib-uninstall` profile the error does not disappear.

I think this should be fixed.
And of course this additional profile should be documented ;)

**Comment by thet** [comment]
Funny thing, I probably did not much testing here and I obviously didn't build the bundles because they can't.

Thanks @ale-rt for this review!

When building bundles there are a lot of dependencies missing - because Patternslib < 3, which we were depending on uses bower.

1) we could add all the dependencies from Patternslib to this package and still stay with Patternslib < 3,
2) or we upgrade to Patternslib >= 3. But there is no stable release and they say that they do not support requirejs anymore (although it looks like if they still do somehow).

I need some more info here how to proceed or if to proceed at all.

@pilz what is the state of Patternslib? Is there a stable release planned?

**Comment by pilz** [comment]
Thanks for bringing this up. We have green tests for a while now and have done extensive manual testing on the jq3 branch  and a month ago we merged up to master. Currently we are preparing to switch all our production sites to Jq3 Patternslib.  We also moved from requirejs to webpack.   For what it’s worth I am planning to do some work on the plone.patternslib package soon.

**Comment by thet** [comment]
Sounds good. But I still see references to ``define`` in the patterns of current Patterns master repository. So I thought, requireJS is still somehow supported?

Regarding plone.patternslib. The PR here should make plone.patternslib obsolete for Plone 5.2, because the pattern requstrations are all done here.

**Comment by pilz** [comment]
I was able to replace requireJS as bundler with webpack while keeping the defines intact. Webpack can also parse them. That meant that I could leave all the patterns boilerplate intact. I don't intend to switch to a different format for the patterns either. So if you want to use requireJS for bundling, I don't see why that shouldn't be possible. 
That said, I am not actively using requireJS, so there might be issues. But I am happy to make changes, as long as they support also webpack.

**Comment by thet** [comment]
This PR is getting obsolete with development on the ES6. There we have all the Patternslib resources at hand, do not need to register any resources in the registry and just need to import individual patterns in a bundle.
https://github.com/plone/plone.staticresources/pull/120

**Pull request closed without merging**
