### PR TITLE
Update it.js

### PR DESCRIPTION
**Pull request by yurj**
propietà -> proprietà (both valid, the second is more used and was already used in Row properties translation)

### CODE REVIEW

**Comment by yurj** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]
+1000

**Comment by ale-rt** [comment]
@yurj please add a file in the news folder called 178.bugfix containing a changelog line. (e.g. `Italian translations have been updated [yurj]`)

**Comment by yurj** [comment]
> @yurj please add a file in the news folder called 178.bugfix containing a changelog line. (e.g. `Italian translations have been updated [yurj]`)

Done, thanks!

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by yurj** [comment]
@jenkins-plone-org please run jobs

**Comment by yurj** [comment]
the failing test are in repoze and unrelated to this commits.

**Comment by yurj** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
