### PR TITLE
Fixed drag problem on click on sortable items in folder contents.

### PR DESCRIPTION
**Pull request by giuliaghisini**
Fixes [https://github.com/plone/Products.CMFPlone/issues/2851](https://github.com/plone/Products.CMFPlone/issues/2851) 

Added a minimum distance to trigger dragging.
Bundles compiled from [https://github.com/plone/mockup/pull/919](https://github.com/plone/mockup/pull/919)

### CODE REVIEW

**Comment by pnicolli** [comment]
@jenkins-plone-org please run jobs

**Comment by pnicolli** [comment]
@frapell is there any chance that this (and therefore [https://github.com/plone/mockup/pull/919](https://github.com/plone/mockup/pull/919)) have been compiled and merged with #41 as well?

**Comment by frapell** [comment]
Hello Piero, yes, I am seeing some "drag" mentions in the code (I included
everything that was in current mockup master)

It should have been excluded?

**Comment by pnicolli** [comment]
It's ok if it's included :) I just wanted to know so we can update this PR to just include the changelog entry :D 
Thanks

**Pull request closed without merging**
