### PR TITLE
Update static resources after alignment fix for Select2-based widgets

### PR DESCRIPTION
**Pull request by davilima6**
Update after changes made in plone/mockup#902

### CODE REVIEW

**Comment by davilima6** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@plone/release-team can we get a new release?

**Comment by davilima6** [comment]
I strongly recommend a 2nd pair of eyes test both widgets before a new release is cut.

**Comment by MrTango** [comment]
looks good to me

**Pull request merged**
