### PR TITLE
Fix problem with TTW compilation of bundles.

### LINKED ISSUE #58: Missing r.js breaks build TTW
It seems the upgrade step `Update the ``last_compilation`` date of all bundles` added in `plone.staticresources@1.2.0` was not enough to bring in the missing `r.js` script. Possibly because the `r.js` folder is missing from [src/plone/staticresources/static/components/](https://github.com/plone/plone.staticresources/tree/master/src/plone/staticresources/static/components)?

## Steps to reproduce
1. Create a new Plone instance of `buildout.coredev`
1. In Resources Registry, enable `Development Mode` and `Save`
1. Open Developer Console, click on `Build` button for any bundle and after confirming the modal see:

```
GET http://localhost:8080/Plone2/++plone++static/components/r.js/dist/r.js net::ERR_ABORTED 404 (Not Found)
Uncaught TypeError: Cannot read property 'optimize' of undefined
    at Object.onLoad (resourceregistry-compiled.js:33643)
    at window.IFrame.load (resourceregistry-compiled.js:33406)
```

### PR DESCRIPTION
**Pull request by thet**
Fixes #58

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by davilima6** [comment]
Jenkins is not making this easy, failed now with:

```
Traceback (most recent call last):
  File "/tmp/shiningpanda4402847161656821372.py", line 189, in <module>
    main()
  File "/tmp/shiningpanda4402847161656821372.py", line 184, in main
    pull_request_handler(pr)
  File "/tmp/shiningpanda4402847161656821372.py", line 68, in __call__
    self._pr_repo()
  File "/tmp/shiningpanda4402847161656821372.py", line 107, in _pr_repo
    self.g_repo = self.g_org.get_repo(self.repo)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/github/Organization.py", line 755, in get_repo
    "/repos/" + self.login + "/" + name
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/github/Requester.py", line 262, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/github/Requester.py", line 372, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/github/Requester.py", line 396, in __requestRaw
    response = cnx.getresponse()
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/github/Requester.py", line 109, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_redirects=False)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /home/jenkins/shiningpanda/jobs/8809464e/virtualenvs/0dd3bfc1/lib/python3.6/site-packages/certifi/cacert.pem
Build step 'Virtualenv Builder' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Robot results publisher started...
-Parsing output xml:
Failed!
/home/jenkins/workspace/pull-request-5.2-3.6@2/parts/test does not exist.
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:505)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:482)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:73)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:54)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3052)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to Node1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at hudson.plugins.robot.RobotParser.parse(RobotParser.java:49)
		at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:221)
		at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:243)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1841)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Email was triggered for: Always
Sending email for trigger: Always
#770 is still in progress; ignoring for purposes of comparison
#770 is still in progress; ignoring for purposes of comparison
Sending email to: davilima6@gmail.com
Finished: FAILURE
```

Retrying...

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@davilima6 @mtrebron the failures as well as the remaining upgrade step are probably due to that line being forgotten in the previous test run: https://github.com/plone/plone.staticresources/pull/61/commits/9e7390e4cad45170607883d1580bec5f22f4ca42#diff-80a60c7c56a3bcf6371329029a2192d9R24

**Comment by davilima6** [comment]
[5.2 job failed with:](https://jenkins.plone.org/job/pull-request-5.2/827/console)

```
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.viewletmanager-3.1.0-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/jenkins/.buildout/eggs/cp27m/Zope-4.1.3-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 126, in __call__
    return self.__func__(__self__, *args, **kw)
  File "/home/jenkins/.buildout/eggs/cp27m/Zope-4.1.3-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 61, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/jenkins/.buildout/eggs/cp27m/zope.pagetemplate-4.4.1-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 135, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/jenkins/.buildout/eggs/cp27m/Zope-4.1.3-py2.7.egg/Products/PageTemplates/engine.py", line 88, in __call__
    return self.template.render(**kwargs)
  File "/home/jenkins/.buildout/eggs/cp27m/z3c.pt-3.2.0-py2.7.egg/z3c/pt/pagetemplate.py", line 173, in render
    return base_renderer(**context)
  File "/home/jenkins/.buildout/eggs/cp27m/Chameleon-3.6.2-py2.7.egg/chameleon/zpt/template.py", line 306, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/jenkins/.buildout/eggs/cp27m/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 209, in render
    raise_with_traceback(exc, tb)
  File "/home/jenkins/.buildout/eggs/cp27m/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 187, in render
    self._render(stream, econtext, rcontext)
  File "/home/jenkins/workspace/pull-request-5.2/var/cache/de1657ec35e96c33d7db31f159d8fa63.py", line 95, in render
    __condition = _static_140631739818768(getitem('view'), econtext, True, ('webstats_js', ))
  File "/home/jenkins/.buildout/eggs/cp27m/Zope-4.1.3-py2.7.egg/Products/PageTemplates/expression.py", line 94, in __call__
    base = self.traverse(base, request, path_items)
  File "/home/jenkins/.buildout/eggs/cp27m/Zope-4.1.3-py2.7.egg/Products/PageTemplates/expression.py", line 65, in traverse
    base, name, path_items[i:], request=request
  File "/home/jenkins/.buildout/eggs/cp27m/zope.traversing-4.3.1-py2.7.egg/zope/traversing/adapters.py", line 156, in traversePathElement
    return traversable.traverse(nm, further_path)
   - __traceback_info__: (<Products.Five.viewlet.metaconfigure.AnalyticsViewlet object at 0x7fe72e2344d0>, 'webstats_js')
  File "/home/jenkins/.buildout/eggs/cp27m/zope.traversing-4.3.1-py2.7.egg/zope/traversing/adapters.py", line 61, in traverse
    raise LocationError(subject, name)
   - __traceback_info__: (<Products.Five.viewlet.metaconfigure.AnalyticsViewlet object at 0x7fe72e2344d0>, 'webstats_js', ())
LocationError: (<Products.Five.viewlet.metaconfigure.AnalyticsViewlet object at 0x7fe72e2344d0>, 'webstats_js')

 - Expression: "view/webstats_js"
 - Filename:   ... /src/plone.app.layout/plone/app/layout/analytics/view.pt
 - Location:   (line 3: col 17)
 - Source:     tal:condition="view/webstats_js"
                              ^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fe75fbe3f10>
               views: <ViewMapper - at 0x7fe72f58bad0>
               modules: <_SecureModuleImporter - at 0x7fe76d1bc190>
               args: <tuple - at 0x7fe777fd5050>
               here: <ImplicitAcquisitionWrapper my-folder at 0x7fe730ccf410>
               wrapped_repeat: <SafeMapping - at 0x7fe72dd89870>
               user: <ImplicitAcquisitionWrapper - at 0x7fe72eff1be0>
               nothing: <NoneType - at 0x55d75b7f2ae0>
               container: <ImplicitAcquisitionWrapper my-folder at 0x7fe730ccf410>
               request: <WSGIRequest - at 0x7fe72dcbe8d0>
               traverse_subpath: <list - at 0x7fe72f8fc730>
               default: <object - at 0x7fe7731d5c40>
               context: <ImplicitAcquisitionWrapper my-folder at 0x7fe730ccf410>
               view: <AnalyticsViewlet plone.analytics at 0x7fe72e2344d0>
               translate: <function translate at 0x7fe72dd70c50>
               root: <ImplicitAcquisitionWrapper  at 0x7fe72d612a00>
               options: {...} (0)
               loop: {...} (0)
               target_language: <NoneType - at 0x55d75b7f2ae0>
| FAIL |
Element 'id=form-buttons-save' did not appear in 30 seconds.
------------------------------------------------------------------------------
Test Datetime Widget                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/jenkins/workspace/pull-request-5.2/parts/test/test_datetime_widget/As_a_contributor_I_can_enter_the_date_and_time/output.xml



Failure in test As a contributor I can enter the date and time (test_datetime_widget.robot)
Traceback (most recent call last):
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/cp27m/robotsuite-2.0.0-py2.7.egg/robotsuite/__init__.py", line 458, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Element 'id=form-buttons-save' did not appear in 30 seconds.

  Ran 7 tests with 1 failures, 0 errors and 0 skipped in 2 minutes 33.674 seconds.
```

I re-ran several times. I'll try once more but if it fails I think we can merge anyway

**Comment by mtrebron** [comment]
I just noticed that TTW bundle compiling does not update the included js stubs. After adding mockup-patterns-select2 and select2 to the plone bundle, saving and compiling, the modal window shows these results (reordered but same as before):
```
FUNCTION
----------------
./++resource++mockup/autotoc/pattern.js
./++resource++mockup/formautofocus/pattern.js
./++resource++mockup/markspeciallinks/pattern.js
./++resource++mockup/cookietrigger/pattern.js
./++resource++mockup/navigationmarker/pattern.js
./++plone++static/components/bootstrap/js/collapse.js
./++plone++static/components/bootstrap/js/dropdown.js
./++plone++static/components/bootstrap/js/tooltip.js
./++resource++mockupjs/utils.js
./++resource++mockup/contentloader/pattern.js
./++resource++mockup/backdrop/pattern.js
./++plone++static/components/jquery-form/src/jquery.form.js
./++resource++mockupjs/i18n.js
./++resource++mockupjs/i18n-wrapper.js
./++resource++mockup/formunloadalert/pattern.js
./++resource++mockup/livesearch/pattern.js
./++resource++mockup/preventdoublesubmit/pattern.js
./++plone++static/components/backbone/backbone.js
./++resource++mockupjs/router.js
./++resource++mockup/modal/pattern.js
./++resource++plone.js
```

**Comment by davilima6** [comment]
@mtrebron , thanks for the report but I think it seems more like a lack of reporting than including in the compiled `plone` bundle. Could you please confirm Select2 is not included? You can inspect the file in: http://localhost:8080/Plone/portal_resources/resource_overrides/static/plone-compiled.js

Unfortunately we lack implementing a decent navigation for those containers in the ZMI, but you can have a look around builds generated through the web with URLs like http://localhost:8080/Plone/portal_resources/resource_overrides/manage_main (they aren't generated in the filesystem like with the `./bin/plone-compile-resources` command)

**Comment by davilima6** [comment]
If that is the case could you please open an issue describing these steps to reproduce?

**Comment by davilima6** [comment]
Tests pass! /o/

**Comment by davilima6** [comment]
@mtrebron , if we confirm a regression it's best to tackle it in a next PR

**Comment by davilima6** [comment]
@thet, @esteele, could you please release?

**Comment by mtrebron** [comment]
> @mtrebron , if we confirm a regression it's best to tackle it in a next PR

Will do once confirmed with the upcoming release

**Pull request merged**
