### PR TITLE
Update bundles (step 9)

### PR DESCRIPTION
**Pull request by vincentfretin**
Update mockup to latest commit. This includes those fixes:
- [x] https://github.com/plone/mockup/pull/990
- [x] https://github.com/plone/mockup/pull/992
- [x] https://github.com/plone/mockup/pull/996
- [x] https://github.com/plone/mockup/issues/997
- [x] https://github.com/plone/mockup/pull/1000
- [x] https://github.com/plone/mockup/pull/1002
- [x] https://github.com/plone/mockup/pull/1003

### CODE REVIEW

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
We may fix other mockup issues, so don't merge this yet.

**Comment by ale-rt** [comment]
Amazing work so far! Thanks a lot :)

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
@mauritsvanrees  You can merge if you're about to release the other packages.

**Comment by mauritsvanrees** [comment]
I have merged, and will do releases now.

**Comment by mauritsvanrees** [comment]
I have released `mockup` 3.2.1 and `plone.staticresources` 1.3.1.

I have updated these versions on the coredev 5.2 branch, but have not pushed it yet. I am doing more releases, and do not want to overload Jenkins.

**Pull request merged**
