### PR TITLE
Upgrade `mockup = 5.0.0-beta.11`

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
I have done a `git rebase --interactive master` fixing up the commits like so:

image

**Review by thet — APPROVED** [review]
LGTM.
Done the commit fixups myself, see comment.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
