### PR TITLE
Remove wrong bundle with typo

### LINKED ISSUE #121: typo in bundlename
upgrade profile 11 has a typo in the bundlename:

https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/upgrades/profiles/11/registry.xml#L24

that's why you get a completely new bundle called `resourceregistryt` after upgrading

### PR DESCRIPTION
**Pull request by petschki**
fixes #121

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]

**Comment by thet** [comment]
LGTM

**Review by thet — CHANGES_REQUESTED** [review]
I think we need this fix also for Plone 5.x, so this should also apply to the 1.x branch of plone.staticresources.
Then I wonder how to handle profile versions. We are currently at 12 for the master branch. What to use for the 1.x branch? @mauritsvanrees do you have an idea how to handle this?

In any case the upgrade step version also be added to ``getNonInstallableProfiles`` here
https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/setuphandlers.py

**Comment by petschki** [comment]
p.staticresources 1.4.1 got released for Plone 5.2.3, so 5.2-latest should be on version 12 too ...

**Review by thet — APPROVED** [review]

**Comment by thet** [comment]
@petschki you're right.
In this case we can safely merge this PR to master and to 1.x at the same time.
However the following is not solved, but also tangles not this PR:
- We're missing an upgrade step for the barceloneta-lts changes on master. Okay-ish for now, as barceloneta-lts is a work in progress.
- What should we do with profile version numbers when we maintain 2 branches of a package? If the barceloneta-lts upgrade step would for example get the version number 14, but profile version should a upgrade step in the 1.x branch get? Thinking about this, maybe we should increase the profile version of plone.staticresources in master branch after merging this PR to 100 or so?

**Comment by thet** [comment]
Oh fine, I just found out that metadata versions were already out of sync in 1.x and master :grimacing: 
Both have upgrades for versions ``12`` but those are just different upgrades.
I will fix that in anther PR.

**Comment by petschki** [comment]
@mauritsvanrees do you know why this master branch did not get checked with Jenkins PR 6.0 ?

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees do you know why this master branch did not get checked with Jenkins PR 6.0 ?

I think there is still stuff missing in Jenkins and/or mr.roboto, or the work is done and the servers need to be updated.
See for example https://github.com/plone/jenkins.plone.org/issues/275

**Pull request merged**
