### PR TITLE
pat-recurrence refactored

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@fredvd is there something wrong with mr.roboto? somehow this PR doesn't have any checks ...

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@fredvd now its there ... nevermind ...

**Comment by fredvd** [comment]
@petschki You mean that it took longer than. Ormal for the notificstions here of the jenkins jobs to appear?  how long did it take approximately?

we haven’t touched mr.roboto in the last 2-3 months afaik.

**Comment by petschki** [comment]
The PR was created 22:17h ... the checks were initiated on 22:58h

**Review by agitator — APPROVED** [review]

**Pull request merged**
