### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by thet**
Together:
https://github.com/plone/plone.staticresources/pull/259
https://github.com/plone/plone.app.dexterity/pull/358

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
Somehow the customplugins `plonelink` and `ploneimage` arent in the tinymce config anymore. Thats why Jenkins is broken. I'll check why and try to fix.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by petschki — APPROVED** [review]

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
Yes, this works. Thanks.
I don't know which upgrade broke the modeleditor: I worked on that last week, and then it was working fine. Any, now it works again.
I am going to check this with the modeleditor in `collective.easyform`, because I fixed that last week as well, and might need a new fix now.

Meanwhile, this PR is missing an upgrade step. Can someone add this?

And a minor thing, but I could fix this after a merge as well: the news snippet is wrong. The asterisks should be removed, as towncrier does this already. And split it into two files, `259.bugfix.1` and `259.bugfix.2`.  Or combine them in one line: upgrade to beta 7, with reference to the both of you.

**Comment by petschki** [comment]
@mauritsvanrees I've fixed the news snipped. Upgrade step is not needed as there are no registry changes.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees I've fixed the news snipped. Upgrade step is not needed as there are no registry changes.

Ah, right, updating the timestamp manually is not needed anymore I think. I am still not completely clear on when an upgrade step is needed now. There might be documentation I need to read. :-)

**Review by mauritsvanrees — APPROVED** [review]

**Comment by thet** [comment]
@mauritsvanrees The modeleditor PR test failures were fixed by this merge. The modeleditor structure change needed this new mockup version... There is a new pat-code-editor which should work better than the previous one (using Highlight.JS to for syntax highlighting allows to highlight while typing, now also the line-numbers should work, and so on)

@petschki @mauritsvanrees thanks for finishing both PRs!

**Pull request merged**
